apiVersion: v1
kind: Service
metadata:
  name: hello-world-v1
  labels:
    app: hello-world-v1
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: NodePort
  selector:
    app: hello-world-v1