apiVersion: v1
kind: Service
metadata:
  name: hello-world-v2
  namespace: default
  labels:
    app: hello-world-v2
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: NodePort
  selector:
    app: hello-world-v2
