apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  clusterName: ""
  name: tls-prod
  namespace: default
spec:
  acme:
    config:
    - dns01:
        provider: clouddns
      domains:
      - exemple.com
      - '*.exemple.com'
  commonName: '*.exemple.com'
  dnsNames:
  - exemple.com
  - '*.exemple.com'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: tls-prod
